
package com.javaws.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSAuthentification", targetNamespace = "http://services.javaws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSAuthentification {


    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validate", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.ValidateResponse")
    @Action(input = "http://services.javaws.com/WSAuthentification/validateRequest", output = "http://services.javaws.com/WSAuthentification/validateResponse")
    public boolean validate(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
