package com.javaws.services;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.Service; // Assurez-vous que c'est la classe correcte de jakarta.xml.ws.Service
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSAuthentificationService", targetNamespace = "http://services.javaws.com/", wsdlLocation = "http://localhost:8083/services/WSAuthentification?wsdl")
public class WSAuthentificationService
    extends Service
{

    private final static URL WSAUTHENTIFICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSAUTHENTIFICATIONSERVICE_EXCEPTION;
    private final static QName WSAUTHENTIFICATIONSERVICE_QNAME = new QName("http://services.javaws.com/", "WSAuthentificationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/WSAuthentification?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSAUTHENTIFICATIONSERVICE_WSDL_LOCATION = url;
        WSAUTHENTIFICATIONSERVICE_EXCEPTION = e;
    }
    
    public WSAuthentificationService() {
        super(null, WSAUTHENTIFICATIONSERVICE_QNAME);
    	
    }

    public WSAuthentificationService(WebServiceFeature... features) {
        super(null, WSAUTHENTIFICATIONSERVICE_QNAME, features);
    }

    public WSAuthentificationService(URL wsdlLocation) {
        super(wsdlLocation, WSAUTHENTIFICATIONSERVICE_QNAME);
    }

    public WSAuthentificationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSAUTHENTIFICATIONSERVICE_QNAME, features);
    }

    public WSAuthentificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSAuthentificationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSAuthentification
     */
    @WebEndpoint(name = "WSAuthentificationPort")
    public WSAuthentification getWSAuthentificationPort() {
        return super.getPort(new QName("http://services.javaws.com/", "WSAuthentificationPort"), WSAuthentification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSAuthentification
     */
    @WebEndpoint(name = "WSAuthentificationPort")
    public WSAuthentification getWSAuthentificationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.javaws.com/", "WSAuthentificationPort"), WSAuthentification.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSAUTHENTIFICATIONSERVICE_EXCEPTION!= null) {
            throw WSAUTHENTIFICATIONSERVICE_EXCEPTION;
        }
        return WSAUTHENTIFICATIONSERVICE_WSDL_LOCATION;
    }

}
